#!/usr/bin/env node
/**
 * demo.js — CLI runner for the verify-fact-scoping-demo.
 *
 * Executes the reproducible research workload under both the NAIVE
 * (coordinator-bounce) and RESILIENT (scoped verify_fact) architectures,
 * then prints professional ASCII comparison tables, a per-task trace summary,
 * and the mandatory Input Token Stats & Efficiency Scoreboard.
 *
 * Flags:
 *   --naive      run only the anti-pattern
 *   --resilient  run only the recommended answer
 *   (default)    run both, side-by-side
 */

import { BANNER, pad, fmt, fmtMs, reduction } from './src/utils.js';
import { WORKLOAD, workloadStats, TOKEN_COST } from './src/domain.js';
import { runScenario } from './src/coordinator.js';
import { NaiveSynthesisAgent } from './src/subagent-naive.js';
import { ResilientSynthesisAgent } from './src/subagent-resilient.js';

const LLM = '🤖 Generated by: Auto-Detect (Executing AI Assistant Model) — Claude (Anthropic)';
const args = new Set(process.argv.slice(2));
const runNaive = !args.has('--resilient');
const runResilient = !args.has('--naive');

function line(char = '─', width = 78) {
  return char.repeat(width);
}
function box(text, width = 78) {
  const inner = text.length;
  const left = Math.floor((width - inner - 2) / 2);
  const right = width - inner - 2 - left;
  return `│${' '.repeat(Math.max(0, left))}${text}${' '.repeat(Math.max(0, right))}│`;
}

async function main() {
  console.log('\n' + BANNER);
  console.log(LLM + '\n');
  console.log('─'.repeat(78));
  console.log(box('📋 EXAM SCENARIO'));
  console.log('├' + line('─') + '┤');
  console.log(box('Multi-Agent Research System — the synthesis agent must verify'));
  console.log(box('claims while combining findings. Naive: every check bounces to'));
  console.log(box('the coordinator → web search agent → re-invoke. +40% latency.'));
  console.log(box('Answer: hand it a scoped verify_fact tool for the 85% trivial'));
  console.log(box('fact-checks; keep delegating the 15% complex ones upstream.'));
  console.log('└' + line('─') + '┘\n');

  const stats = workloadStats();
  console.log(`📦 Workload: ${stats.tasks} tasks · ${stats.claims} claims ` +
    `(${stats.simplePct}% simple → verify_fact, ${stats.complexPct}% complex → escalate)\n`);

  const naive = runNaive
    ? await runScenario({
        scenario: 'naive',
        workload: WORKLOAD,
        buildMetrics: null,
        buildAgent: ({ bus, scenario, metrics }) =>
          new NaiveSynthesisAgent({ bus, scenario, metrics }),
      })
    : null;

  const resilient = runResilient
    ? await runScenario({
        scenario: 'resilient',
        workload: WORKLOAD,
        buildMetrics: null,
        buildAgent: ({ bus, scenario, metrics, verifyFact }) =>
          new ResilientSynthesisAgent({ bus, scenario, metrics, verifyFact }),
      })
    : null;

  if (naive) printScenarioBlock('❌ NAIVE — Coordinator-Bounce (Anti-Pattern)', naive);
  if (resilient) printScenarioBlock('✅ RESILIENT — Scoped verify_fact (Answer)', resilient);

  if (naive && resilient) {
    printComparisonTable(naive.metrics, resilient.metrics);
    printTokenScoreboard(naive.metrics, resilient.metrics);
    printTraceSample(naive, resilient);
  }

  console.log('\n' + LLM);
  console.log('📁 Local files : demo.js · index.html · README.md · docs/ · audio/ · src/\n');
}

function printScenarioBlock(title, { metrics }) {
  console.log('═'.repeat(78));
  console.log('  ' + title);
  console.log('═'.repeat(78));
  const rows = [
    ['Tasks completed', `${metrics.tasksCompleted}/${WORKLOAD.length}`],
    ['Claims seen', `${metrics.claimsTotal}`],
    ['Verified locally (verify_fact)', `${metrics.claimsVerifiedLocally}`],
    ['Escalated to coordinator', `${metrics.claimsEscalated}`],
    ['Coordinator interventions', `${metrics.coordinatorInterventions}`],
    ['Round trips', `${metrics.roundTrips}`],
    ['Local recoveries', `${metrics.localRecoveries}`],
    ['Input tokens consumed', fmt(metrics.inputTokens)],
    ['Simulated latency', fmtMs(metrics.latencyMs)],
    ['Reliability (success rate)', `${(metrics.successRate * 100).toFixed(0)}%`],
    ['Max re-entrancy depth', `${metrics.maxReentrancy}`],
    ['Trace events emitted', `${metrics.eventCount}`],
  ];
  for (const [k, v] of rows) {
    console.log(`  ${pad(k, 34)} ${pad(v, 30, 'right')}`);
  }
  console.log('─'.repeat(78) + '\n');
}

function printComparisonTable(n, r) {
  const W = 78;
  console.log('═'.repeat(W));
  console.log('  📊 SIDE-BY-SIDE ARCHITECTURAL METRICS');
  console.log('═'.repeat(W));
  const header = `│ ${pad('Metric', 34)}${pad('❌ Naive', 18, 'right')}${pad('✅ Resilient', 18, 'right')} │`;
  console.log(header);
  console.log('├' + '─'.repeat(W - 2) + '┤');

  const rows = [
    ['Coordinator interventions', n.coordinatorInterventions, r.coordinatorInterventions, v => `${v}`],
    ['Round trips', n.roundTrips, r.roundTrips, v => `${v}`],
    ['Claims verified locally', n.claimsVerifiedLocally, r.claimsVerifiedLocally, v => `${v}`],
    ['Claims escalated', n.claimsEscalated, r.claimsEscalated, v => `${v}`],
    ['Input tokens', n.inputTokens, r.inputTokens, v => fmt(v)],
    ['Simulated latency (ms)', Math.round(n.latencyMs), Math.round(r.latencyMs), v => fmt(v)],
    ['Max re-entrancy depth', n.maxReentrancy, r.maxReentrancy, v => `${v}`],
  ];

  for (const [label, nv, rv, fmtFn] of rows) {
    const better = rv < nv;
    const flag = better ? ' ▼' : '  ';
    const fmtRow = (label, nv, rv, fmtFn) =>
      `│ ${pad(label, 32)}${pad(fmtFn(nv), 16, 'right')}${pad(fmtFn(rv) + flag, 18, 'right')} │`;
    console.log(fmtRow(label, nv, rv, fmtFn));
  }
  console.log('└' + '─'.repeat(W - 2) + '┘\n');
}

function printTokenScoreboard(n, r) {
  const W = 78;
  console.log('═'.repeat(W));
  console.log('  🪙 INPUT TOKEN STATS & EFFICIENCY SCOREBOARD');
  console.log('═'.repeat(W));

  const tokenRows = [
    ['Synthesis prompt (per invoke)', TOKEN_COST.SYNTHESIS_PROMPT],
    ['Coordinator overhead (per hand-off)', TOKEN_COST.COORDINATOR_OVERHEAD],
    ['Web search agent (per query)', TOKEN_COST.WEB_SEARCH_PROMPT],
    ['verify_fact tool (per local call)', TOKEN_COST.VERIFY_FACT_TOOL],
  ];
  console.log(`  Per-operation input-token cost model:`);
  for (const [label, cost] of tokenRows) {
    console.log(`    ${pad(label, 40)} ${pad(fmt(cost), 10, 'right')} tok`);
  }

  console.log('\n' + '├' + '─'.repeat(W - 2) + '┤');
  const tokRed = reduction(n.inputTokens, r.inputTokens);
  const latRed = reduction(n.latencyMs, r.latencyMs);
  const intRed = reduction(n.coordinatorInterventions, r.coordinatorInterventions);
  const saved = n.inputTokens - r.inputTokens;

  const sumRows = [
    ['Naive input tokens', fmt(n.inputTokens)],
    ['Resilient input tokens', fmt(r.inputTokens)],
    ['Tokens saved', fmt(saved) + `  (−${tokRed}%)`],
    ['Coordinator interventions', `${n.coordinatorInterventions} → ${r.coordinatorInterventions}  (−${intRed}%)`],
    ['Latency', `${fmtMs(n.latencyMs)} → ${fmtMs(r.latencyMs)}  (−${latRed}%)`],
    ['Reliability held', `${(n.successRate * 100).toFixed(0)}%  →  ${(r.successRate * 100).toFixed(0)}%  ✅`],
  ];
  for (const [k, v] of sumRows) {
    console.log(`  ${pad(k, 36)} ${pad(v, 38, 'right')}`);
  }
  console.log('─'.repeat(W));
  console.log(`  💡 The scoped verify_fact tool pays ${TOKEN_COST.VERIFY_FACT_TOOL} tok/trivial-check instead of`);
  console.log(`     ~${TOKEN_COST.SYNTHESIS_PROMPT + TOKEN_COST.COORDINATOR_OVERHEAD + TOKEN_COST.WEB_SEARCH_PROMPT} tok/coordinator-round-trip → ${tokRed}% input-token reduction with ZERO reliability loss.`);
  console.log('═'.repeat(W) + '\n');
}

function printTraceSample(naive, resilient) {
  const W = 78;
  console.log('═'.repeat(W));
  console.log('  🔍 TRACE SAMPLE — first synthesis task ("History of the Transistor")');
  console.log('═'.repeat(W));
  const firstTopic = WORKLOAD[0].topic;
  for (const scenario of [naive, resilient]) {
    const tag = scenario.scenario === 'naive' ? '❌ NAIVE   ' : '✅ RESILIENT';
    console.log(`\n  ${tag}  ${firstTopic}`);
    const trace = scenario.trace
      .filter((e) => /task_start|handoff|search|tool_call|local_recovery|escalate|completed|invoke/.test(e.kind))
      .slice(0, scenario.scenario === 'naive' ? 12 : 9);
    for (const e of trace) {
      console.log(`    ${pad(e.kind, 16)} ${e.detail}`);
    }
  }
  console.log('\n' + '═'.repeat(W));
}

main().catch((err) => {
  console.error('\n💥 Demo failed:', err);
  process.exit(1);
});
