/**
 * utils.js — Helpers: deterministic latency simulation, structured logging,
 * event tracing, formatters, and a tiny EventEmitter used to broadcast
 * architectural events to the CLI demo, the web simulator and the metrics
 * scoreboard. Zero runtime dependencies (pure Node ESM).
 */

/** Deterministic, interruptible sleep. Keeps timings reproducible in tests. */
export function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, Math.max(0, ms)));
}

/** Clamp a number into a range. */
export function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

/** Pad a string to a fixed visual width for ASCII tables. */
export function pad(value, width, align = 'left') {
  const str = String(value ?? '');
  if (str.length >= width) return str.slice(0, width);
  const gap = ' '.repeat(width - str.length);
  return align === 'right' ? gap + str : str + gap;
}

/** Format a number with thousands separators. */
export function fmt(n) {
  if (n === null || n === undefined || Number.isNaN(n)) return '—';
  return Number(n).toLocaleString('en-US');
}

/** Format milliseconds as a compact human string. */
export function fmtMs(ms) {
  if (ms < 1000) return `${Math.round(ms)} ms`;
  const s = ms / 1000;
  if (s < 60) return `${s.toFixed(2)} s`;
  const m = Math.floor(s / 60);
  return `${m}m ${Math.round(s - m * 60)}s`;
}

/** Percentage of `part` relative to `whole`, rounded to 1 decimal. */
export function pct(part, whole) {
  if (!whole) return 0;
  return Number((((part / whole) * 100)).toFixed(1));
}

/** Reduction percentage (how much smaller `better` is vs `worse`). */
export function reduction(worse, better) {
  if (!worse) return 0;
  return Number((((worse - better) / worse) * 100).toFixed(1));
}

/**
 * Tiny synchronous-ish event bus. Producers push structured events
 * (traces); consumers (CLI printer, future web fetch of trace.json) subscribe.
 */
export class EventBus {
  constructor() {
    this._subs = [];
    this.log = [];
  }
  subscribe(fn) {
    this._subs.push(fn);
    return () => {
      this._subs = this._subs.filter((f) => f !== fn);
    };
  }
  /** Emit an architectural event: { ts, layer, scenario, kind, detail, tokens, latencyMs } */
  emit(event) {
    const enriched = {
      ts: Date.now(),
      layer: 'unknown',
      scenario: 'unknown',
      kind: 'event',
      tokens: 0,
      latencyMs: 0,
      ...event,
    };
    this.log.push(enriched);
    for (const fn of this._subs) {
      try {
        fn(enriched);
      } catch {
        /* subscriber faults must never break the simulation */
      }
    }
  }
}

/** Build an empty, strongly-shaped metrics aggregate for a scenario run. */
export function emptyMetrics() {
  return {
    scenario: 'unknown',
    tasksCompleted: 0,
    tasksFailed: 0,
    claimsTotal: 0,
    claimsVerifiedLocally: 0, // resolved by the scoped verify_fact tool
    claimsEscalated: 0, // delegated up to the coordinator → web search agent
    coordinatorInterventions: 0, // times the coordinator had to broker a hand-off
    roundTrips: 0, // synthesis ↔ coordinator ↔ web-search round trips
    localRecoveries: 0, // transient lookups recovered without escalation
    inputTokens: 0, // total prompt input tokens consumed
    outputTokens: 0,
    latencyMs: 0, // simulated wall-clock latency
    successRate: 0, // 0..1
    maxReentrancy: 0, // deepest observed re-invocation depth (loop safety)
    eventCount: 0,
  };
}

/** Add two metric objects (used when aggregating across tasks). */
export function addMetrics(a, b) {
  const out = { ...a };
  for (const key of Object.keys(b)) {
    if (typeof b[key] === 'number') out[key] = (out[key] || 0) + b[key];
  }
  out.scenario = b.scenario || a.scenario;
  out.successRate = a.claimsTotal + b.claimsTotal
    ? (a.claimsVerifiedLocally + a.claimsEscalated + b.claimsVerifiedLocally + b.claimsEscalated) /
      (a.claimsTotal + b.claimsTotal)
    : 0;
  return out;
}

export const LLM_ATTRIBUTION = '🤖 Generated by: Auto-Detect (Executing AI Assistant Model) — Claude (Anthropic)';

export const BANNER = String.raw`
 __     ___    ____   ___ ___ _   _ _____ ____  ___  _____ ____
 \ \   / / |  |  _ \ / _ \_ _| \ | | ____/ ___||_ _|| ____|  _ \
  \ \ / /| |  | |_) | | | | ||  \| |  _| \___ \ | | |  _| | |_) |
   \ V / | |  |  _ <| |_| | || |\  | |___ ___) || | | |___|  _ <
    \_/  |_|  |_| \_\\___/___|_| \_|_____|____/|___||_____|_| \_\

   Multi-Agent Research System  ·  Scoped verify_fact Tool Demo
   Claude AI Architect Exam — Naive Coordinator-Bounce  vs.  Resilient Least-Privilege Scoping
`;
